#!/bin/bash
# SessionStart hook for Claude Code cloud sessions:
# install OpenRefine next to orcli (required by `orcli run` and `orcli test`)
# and bashly (required to regenerate orcli from src/)
set -euo pipefail

if [[ "${CLAUDE_CODE_REMOTE:-}" != "true" ]]; then
  exit 0
fi

OPENREFINE_VERSION="3.10.1"

cd "${CLAUDE_PROJECT_DIR}"

# OpenRefine (same files as in .devcontainer/devcontainer.json, ignored by .gitignore)
if [[ ! -x refine ]] || [[ "$(cat webapp/.openrefine-version 2>/dev/null)" != "${OPENREFINE_VERSION}" ]]; then
  rm -rf refine refine.ini server webapp
  curl -fsSL "https://github.com/OpenRefine/OpenRefine/releases/download/${OPENREFINE_VERSION}/openrefine-linux-${OPENREFINE_VERSION}.tar.gz" |
    tar --exclude 'licenses' --exclude 'LICENSE.txt' --exclude 'licenses.xml' --exclude 'README.md' -xz --strip 1
  echo "${OPENREFINE_VERSION}" > webapp/.openrefine-version
fi

# bashly (same version that generated ./orcli, to avoid unrelated diffs on regeneration)
BASHLY_VERSION="$(grep -m 1 -oP 'generated by bashly \K[0-9.]+' orcli)"
if ! gem list -i bashly -v "${BASHLY_VERSION}" &>/dev/null; then
  gem install --silent bashly -v "${BASHLY_VERSION}"
fi
GEM_BINDIR="$(ruby -e 'puts Gem.bindir')"

if [[ -n "${CLAUDE_ENV_FILE:-}" ]]; then
  echo "export PATH=\"${GEM_BINDIR}:\${PATH}\"" >> "${CLAUDE_ENV_FILE}"
  # UTF-8 locale (tests/import-csv-unicode.sh fails with the default POSIX locale)
  echo 'export LANG=C.UTF-8 LC_ALL=C.UTF-8' >> "${CLAUDE_ENV_FILE}"
fi
