# https://gitpod.io/#https://github.com/opencultureconsulting/orcli
tasks:
  - name: install bashly and OpenRefine
    before: gem install --silent bashly
    init: |
      wget -q -O openrefine.tar.gz "https://oss.sonatype.org/service/local/artifact/maven/content?r=releases&g=org.openrefine&a=openrefine&v=3.6.2&c=linux&p=tar.gz"
      tar --exclude 'licenses' --exclude 'LICENSE.txt' --exclude 'README.md'  -xzf openrefine.tar.gz --strip 1
      rm openrefine.tar.gz
    command: |
      sudo ln -s "${PWD}/orcli" /usr/local/bin/
      source <(orcli completions)
      ./refine

ports:
  - port: 3333
    onOpen: notify
    visibility: private

vscode:
  extensions:
    - timonwong.shellcheck
    - foxundermoon.shell-format
